Repository oognuyh/algorithm-study, pull requests merged in 2022-05, with the labels that each got.

#17 reformat java files
  BOJ2480/bb.java
  BOJ2480/dd.java
Labels: reformat

#19 reformat java files
  BOJ2480/bb.java
Labels: reformat

#21 reformat java files
  BOJ2480/bb.java
Labels: reformat

#22 reformat java files
  BOJ2480/cc.java
Labels: auto

#23 reformat java files
  BOJ2480/cc.java
Labels: auto

#81 solve P92334 (#75)
  P92334/Nohtaewon.java
Labels: try again later
